export const RICH_BLOG_TOPICS = [
    {
    "slug": "sunset-camel-ride-souss-massa",
    "image": "https://images.unsplash.com/photo-1549488344-c36142751f8a?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 35,
    "en": {
    "title": "Golden Hour: Sunset Camel Ride in Souss Massa",
    "desc": "Experience the magic of the Souss Massa National Park as the sun dips below the horizon on a traditional camel trek.",
    "fullBody": "Escape the city noise and immerse yourself in the serene rhythm of the Souss Massa National Park. As the sky turns shades of violent and orange, the eucalyptus forests release a refreshing scent, creating an atmosphere of pure tranquility. This isn't just a ride; it's a connection with the ancient Berber mode of transport in a protected biosphere reserve.\n\nUnlike the crowded city beaches, this route takes you through the estuary where the Oued Souss meets the Atlantic. Keep your eyes peeled for Greater Flamingos and Bald Ibises, as this park is a sanctuary for rare birdlife. Your guide will likely offer you fresh dates and mint tea midway through the dunes, a staple of Moroccan hospitality.\n\nPractical advice: The Atlantic breeze picks up significantly at sunset, so bring a light windbreaker or sweater even in summer. Wear long pants to avoid chafing against the saddle. The best light for photography is usually around 7:00 PM in summer and 5:30 PM in winter."
    },
    "fr": {
    "title": "Heure Dorée : Balade à Dos de Chameau à Souss Massa",
    "desc": "Vivez la magie du parc national de Souss Massa alors que le soleil plonge sous l'horizon lors d'une méharée traditionnelle.",
    "fullBody": "Échappez au bruit de la ville et immergez-vous dans le rythme serein du parc national de Souss Massa. Alors que le ciel se pare de teintes violettes et orangées, les forêts d'eucalyptus libèrent un parfum rafraîchissant, créant une atmosphère de pure tranquillité. Ce n'est pas une simple promenade, mais une connexion avec l'ancien mode de transport berbère au cœur d'une réserve de biosphère protégée.\n\nContrairement aux plages bondées de la ville, cet itinéraire vous emmène à travers l'estuaire où l'Oued Souss rencontre l'Atlantique. Ouvrez l'œil pour apercevoir des flamants roses et des ibis chauves, car ce parc est un sanctuaire pour les oiseaux rares. Votre guide vous offrira probablement des dattes fraîches et du thé à la menthe au milieu des dunes, un incontournable de l'hospitalité marocaine.\n\nConseils pratiques : La brise atlantique se lève significativement au coucher du soleil, apportez donc un coupe-vent léger ou un pull, même en été. Portez un pantalon long pour éviter les frottements sur la selle. La meilleure lumière pour la photographie se situe généralement vers 19h00 en été et 17h30 en hiver."
    },
    "es": {
    "title": "Hora Dorada: Paseo en Camello al Atardecer en Souss Massa",
    "desc": "Experimenta la magia del Parque Nacional Souss Massa mientras el sol se hunde bajo el horizonte en una travesía tradicional en camello.",
    "fullBody": "Escapa del ruido de la ciudad y sumérgete en el ritmo sereno del Parque Nacional Souss Massa. A medida que el cielo se tiñe de violeta y naranja, los bosques de eucaliptos liberan un aroma refrescante, creando una atmósfera de pura tranquilidad. No es solo un paseo; es una conexión con el antiguo medio de transporte bereber en una reserva de la biosfera protegida.\n\nA diferencia de las concurridas playas de la ciudad, esta ruta te lleva a través del estuario donde el Oued Souss se encuentra con el Atlántico. Mantén los ojos bien abiertos para ver flamencos rosados e ibis calvos, ya que este parque es un santuario para aves raras. Es probable que tu guía te ofrezca dátiles frescos y té a la menta en medio de las dunas, un elemento básico de la hospitalidad marroquí.\n\nConsejo práctico: La brisa del Atlántico aumenta significativamente al atardecer, así que lleva un cortavientos ligero o un jersey incluso en verano. Usa pantalones largos para evitar rozaduras con la silla de montar. La mejor luz para la fotografía suele ser alrededor de las 19:00 en verano y las 17:30 en invierno."
    }
    },
    {
    "slug": "paradise-valley-agadir-swimming",
    "image": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 25,
    "en": {
    "title": "Hidden Oasis: Day Trip to Paradise Valley",
    "desc": "Discover the turquoise natural pools and limestone canyons of Paradise Valley, a refreshing escape just outside Agadir.",
    "fullBody": "Nestled in the High Atlas mountains, Paradise Valley lives up to its name with emerald-green waters contrasting against ancient red limestone rocks. The atmosphere is laid-back and earthy; it's a place where time slows down, and the only sound is the trickling of the Tamraght River. It feels worlds away from the coastal bustle, offering a true oasis experience.\n\nLocated about 40 minutes drive from Agadir, the valley is famous for its natural swimming holes. Locals set up plastic chairs right in the shallow riverbeds where you can sip orange juice with your feet in the water. For the adventurous, there are several cliff-jumping spots, but always verify the water depth with a local guide before jumping.\n\nPractical advice: The hike from the parking area to the pools takes about 20 minutes on uneven terrain, so wear sturdy sandals or sneakers, not flip-flops. The best time to visit is mid-week to avoid the weekend crowds. Note that in late summer (August/September), water levels can drop significantly due to drought."
    },
    "fr": {
    "title": "Oasis Cachée : Excursion à la Vallée du Paradis",
    "desc": "Découvrez les piscines naturelles turquoise et les canyons calcaires de la Vallée du Paradis, une évasion rafraîchissante aux portes d'Agadir.",
    "fullBody": "Nichée dans les montagnes du Haut Atlas, la Vallée du Paradis porte bien son nom avec ses eaux vert émeraude contrastant avec les anciennes roches calcaires rouges. L'atmosphère y est détendue et authentique ; c'est un endroit où le temps ralentit, bercé par le ruissellement de la rivière Tamraght. On se sent à des années-lumière de l'agitation côtière, vivant une véritable expérience d'oasis.\n\nSituée à environ 40 minutes de route d'Agadir, la vallée est célèbre pour ses trous d'eau naturels. Les habitants installent des chaises en plastique directement dans le lit peu profond de la rivière où vous pouvez siroter un jus d'orange les pieds dans l'eau. Pour les aventureux, il y a plusieurs points de saut depuis les falaises, mais vérifiez toujours la profondeur de l'eau avec un guide local avant de sauter.\n\nConseils pratiques : La marche du parking aux piscines prend environ 20 minutes sur un terrain accidenté, portez donc des sandales robustes ou des baskets, pas de tongs. Le meilleur moment pour visiter est en milieu de semaine pour éviter la foule du week-end. Notez qu'en fin d'été (août/septembre), le niveau de l'eau peut baisser considérablement en raison de la sécheresse."
    },
    "es": {
    "title": "Oasis Escondido: Excursión al Valle del Paraíso",
    "desc": "Descubre las piscinas naturales turquesas y los cañones de piedra caliza del Valle del Paraíso, una escapada refrescante a las afueras de Agadir.",
    "fullBody": "Ubicado en las montañas del Alto Atlas, el Valle del Paraíso hace honor a su nombre con aguas verde esmeralda que contrastan con antiguas rocas calizas rojas. El ambiente es relajado y terrenal; es un lugar donde el tiempo se detiene y el único sonido es el goteo del río Tamraght. Se siente a mundos de distancia del ajetreo costero, ofreciendo una verdadera experiencia de oasis.\n\nSituado a unos 40 minutos en coche de Agadir, el valle es famoso por sus pozas naturales. Los lugareños colocan sillas de plástico directamente en los lechos poco profundos del río donde puedes tomar zumo de naranja con los pies en el agua. Para los aventureros, hay varios puntos para saltar desde los acantilados, pero verifica siempre la profundidad del agua con un guía local antes de saltar.\n\nConsejo práctico: La caminata desde el aparcamiento hasta las piscinas dura unos 20 minutos por terreno irregular, así que usa sandalias resistentes o zapatillas de deporte, no chanclas. El mejor momento para visitar es a mitad de semana para evitar las multitudes del fin de semana. Ten en cuenta que a finales de verano (agosto/septiembre), los niveles de agua pueden bajar significativamente debido a la sequía."
    }
    },
    {
    "slug": "surfing-anchor-point-taghazout",
    "image": "https://images.unsplash.com/photo-1531129598836-e8d1979b942f?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 50,
    "en": {
    "title": "Ride the Waves: Surfing at Anchor Point",
    "desc": "Catch world-class waves at Taghazout's legendary Anchor Point, the surfing capital of Morocco.",
    "fullBody": "The vibe in Taghazout is unmistakably surf-centric, blending Berber culture with a laid-back Californian ethos. At Anchor Point, the energy is electric as surfers from around the globe gather to watch the sets roll in. The crashing Atlantic waves against the rocky promontory create a raw, powerful backdrop that captivates both pros and beginners watching from the cliffs.\n\nAnchor Point is known for its long right-hand point break that can hold massive swells, especially during winter. Even if you aren't surfing the big waves, the nearby Panorama Beach offers gentler breaks for learners. After your session, head to 'World of Waves' or 'Amouage' for a protein shake and watch the sunset over the fishing boats returning to shore.\n\nPractical advice: The prime surfing season is from October to April when the winter swells hit the coast. A 3/2mm wetsuit is sufficient for most of the year, but a 4/3mm is recommended for early mornings in January. Be wary of the rocky entry at Anchor Point; timing your jump out is crucial to save your feet (and your board)."
    },
    "fr": {
    "title": "Domptez les Vagues : Surf à Anchor Point",
    "desc": "Attrapez des vagues de classe mondiale au légendaire Anchor Point de Taghazout, la capitale du surf au Maroc.",
    "fullBody": "L'ambiance à Taghazout est indéniablement centrée sur le surf, mélangeant la culture berbère avec un esprit californien décontracté. À Anchor Point, l'énergie est électrique alors que des surfeurs du monde entier se rassemblent pour observer les séries. Le fracas des vagues de l'Atlantique contre le promontoire rocheux crée une toile de fond brute et puissante qui captive tant les pros que les débutants observant depuis les falaises.\n\nAnchor Point est connu pour sa longue droite qui peut supporter une houle massive, surtout en hiver. Même si vous ne surfez pas les grosses vagues, la plage Panorama toute proche offre des vagues plus douces pour les apprenants. Après votre session, dirigez-vous vers 'World of Waves' ou 'Amouage' pour un shake protéiné et regardez le coucher de soleil sur les bateaux de pêche rentrant au port.\n\nConseils pratiques : La saison de surf idéale s'étend d'octobre à avril, lorsque la houle hivernale frappe la côte. Une combinaison 3/2mm est suffisante pour la majeure partie de l'année, mais une 4/3mm est recommandée pour les petits matins de janvier. Méfiez-vous de l'entrée rocheuse à Anchor Point ; bien chronométrer votre mise à l'eau est crucial pour épargner vos pieds (et votre planche)."
    },
    "es": {
    "title": "Cabalga las Olas: Surf en Anchor Point",
    "desc": "Coge olas de clase mundial en el legendario Anchor Point de Taghazout, la capital del surf en Marruecos.",
    "fullBody": "El ambiente en Taghazout está inconfundiblemente centrado en el surf, mezclando la cultura bereber con un estilo californiano relajado. En Anchor Point, la energía es eléctrica mientras surfistas de todo el mundo se reúnen para ver llegar las series. El choque de las olas del Atlántico contra el promontorio rocoso crea un telón de fondo crudo y poderoso que cautiva tanto a profesionales como a principiantes que miran desde los acantilados.\n\nAnchor Point es conocido por su larga ola derecha que puede aguantar un oleaje masivo, especialmente durante el invierno. Incluso si no surfeas las olas grandes, la cercana playa Panorama ofrece rompientes más suaves para aprendices. Después de tu sesión, dirígete a 'World of Waves' o 'Amouage' para un batido de proteínas y contempla la puesta de sol sobre los barcos de pesca que regresan a la orilla.\n\nConsejo práctico: La temporada principal de surf es de octubre a abril, cuando el oleaje invernal llega a la costa. Un traje de neopreno 3/2mm es suficiente para la mayor parte del año, pero se recomienda un 4/3mm para las mañanas tempranas de enero. Ten cuidado con la entrada rocosa en Anchor Point; calcular bien tu salto al agua es crucial para salvar tus pies (y tu tabla)."
    }
    },
    {
    "slug": "souk-el-had-shopping-agadir",
    "image": "https://images.unsplash.com/photo-1542044801-30d3e45ae49a?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 15,
    "en": {
    "title": "Souk El Had: The Ultimate Agadir Shopping Guide",
    "desc": "Navigate the largest urban market in Africa with our insider guide to spices, leather, and Argan oil.",
    "fullBody": "Walking into Souk El Had is a sensory overload in the best way possible. With over 3,000 stalls, the air is thick with the smell of cumin, tanned leather, and fresh mint. Unlike the tourist-heavy souks of Marrakech, this is where Agadir's locals shop, giving it a gritty, authentic bustling atmosphere. It is a walled city within a city, organized by trade, preventing you from getting hopelessly lost.\n\nHead straight to the 'Gate 6' entrance for the spice market. Here, look for 'Ras el Hanout', a complex blend of up to 35 spices perfect for tagines. Be cautious when buying Argan oil; ask for the 'cosmetic' version (lighter) or 'culinary' (toasted nutty smell). Authentic sellers will often let you taste the culinary oil with bread before you buy.\n\nPractical advice: The Souk is closed on Mondays for cleaning, so plan your visit for Tuesday through Sunday. Cash is king here; credit cards are rarely accepted. Haggling is expected but keep it polite—aiming for 30-40% off the initial asking price is a good rule of thumb. Watch your pockets in the crowded narrow aisles."
    },
    "fr": {
    "title": "Souk El Had : Le Guide Ultime du Shopping à Agadir",
    "desc": "Naviguez dans le plus grand marché urbain d'Afrique avec notre guide d'initié sur les épices, le cuir et l'huile d'Argan.",
    "fullBody": "Entrer dans le Souk El Had est une surcharge sensorielle de la meilleure des manières. Avec plus de 3 000 étals, l'air est chargé d'odeurs de cumin, de cuir tanné et de menthe fraîche. Contrairement aux souks très touristiques de Marrakech, c'est ici que les habitants d'Agadir font leurs achats, ce qui lui confère une atmosphère authentique et bouillonnante. C'est une ville fortifiée dans la ville, organisée par métier, ce qui vous évite de vous perdre désespérément.\n\nDirigez-vous directement vers l'entrée 'Porte 6' pour le marché aux épices. Ici, cherchez le 'Ras el Hanout', un mélange complexe de jusqu'à 35 épices, parfait pour les tajines. Soyez prudent lors de l'achat d'huile d'Argan ; demandez la version 'cosmétique' (plus claire) ou 'culinaire' (odeur de noisette grillée). Les vendeurs authentiques vous laisseront souvent goûter l'huile culinaire avec du pain avant d'acheter.\n\nConseils pratiques : Le Souk est fermé le lundi pour le nettoyage, prévoyez donc votre visite du mardi au dimanche. L'argent liquide est roi ici ; les cartes de crédit sont rarement acceptées. Le marchandage est attendu mais restez poli — viser 30 à 40 % de réduction sur le prix initial est une bonne règle de base. Surveillez vos poches dans les allées étroites et bondées."
    },
    "es": {
    "title": "Souk El Had: La Guía Definitiva de Compras en Agadir",
    "desc": "Navega por el mercado urbano más grande de África con nuestra guía experta sobre especias, cuero y aceite de Argán.",
    "fullBody": "Entrar en Souk El Had es una sobrecarga sensorial en el mejor sentido posible. Con más de 3.000 puestos, el aire está denso con el olor a comino, cuero curtido y menta fresca. A diferencia de los zocos turísticos de Marrakech, aquí es donde compran los habitantes de Agadir, lo que le da una atmósfera auténtica y bulliciosa. Es una ciudad amurallada dentro de una ciudad, organizada por gremios, evitando que te pierdas irremediablemente.\n\nDirígete directamente a la entrada 'Puerta 6' para el mercado de especias. Aquí, busca el 'Ras el Hanout', una mezcla compleja de hasta 35 especias perfecta para tajines. Ten cuidado al comprar aceite de Argán; pide la versión 'cosmética' (más clara) o 'culinaria' (olor a nuez tostada). Los vendedores auténticos a menudo te dejarán probar el aceite culinario con pan antes de comprar.\n\nConsejo práctico: El Zoco cierra los lunes por limpieza, así que planifica tu visita de martes a domingo. El efectivo es el rey aquí; rara vez se aceptan tarjetas de crédito. Se espera el regateo, pero mantén la educación: aspirar a un 30-40% de descuento sobre el precio inicial es una buena regla general. Vigila tus bolsillos en los pasillos estrechos y concurridos."
    }
    },
    {
    "slug": "hot-air-balloon-marrakech-atlas",
    "image": "https://images.unsplash.com/photo-1541355796918-0904d9b6264d?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 180,
    "en": {
    "title": "Sky High: Hot Air Balloon Over the Atlas",
    "desc": "Witness the sunrise over the foothills of the Atlas Mountains on an unforgettable hot air balloon flight from Marrakech.",
    "fullBody": "There is a profound silence that comes with floating 3,000 feet above the earth, broken only by the occasional blast of the burner. As you drift over the Jbilet mountains north of Marrakech, the landscape changes from rocky desert to lush olive groves. The contrast of the red earth against the snow-capped Atlas Mountains in the distance creates a photographer's dream canvas.\n\nThe experience is luxurious from start to finish. You are collected from Agadir in the very early hours to arrive in Marrakech by dawn. Upon landing, it is tradition to enjoy a 'Berber Breakfast' in a royal tent, featuring msemmen (pancakes), local honey, and fresh mint tea, often hosted by residents of the local villages you just flew over.\n\nPractical advice: This is a full-day commitment from Agadir due to the travel time (3 hours each way to the launch site). The wake-up call is usually around 4:00 AM. Dress in layers; it is freezing in the pre-dawn desert air, but the balloon basket gets quite warm once the sun is up and the burners are firing."
    },
    "fr": {
    "title": "Ciel Ouvert : Montgolfière au-dessus de l'Atlas",
    "desc": "Assistez au lever du soleil sur les contreforts de l'Atlas lors d'un vol inoubliable en montgolfière au départ de Marrakech.",
    "fullBody": "Il règne un silence profond lorsque l'on flotte à 1 000 mètres au-dessus de la terre, rompu seulement par le souffle occasionnel du brûleur. En dérivant au-dessus des montagnes Jbilet au nord de Marrakech, le paysage change du désert rocailleux aux oliveraies luxuriantes. Le contraste de la terre rouge avec les montagnes de l'Atlas enneigées au loin crée une toile de rêve pour les photographes.\n\nL'expérience est luxueuse du début à la fin. Vous êtes pris en charge à Agadir aux premières heures pour arriver à Marrakech à l'aube. À l'atterrissage, la tradition veut que l'on déguste un 'petit-déjeuner berbère' sous une tente royale, avec des msemmen (crêpes), du miel local et du thé à la menthe frais, souvent accueilli par les résidents des villages que vous venez de survoler.\n\nConseils pratiques : C'est un engagement d'une journée complète au départ d'Agadir en raison du temps de trajet (3 heures aller simple jusqu'au site de lancement). Le réveil est généralement vers 4h00 du matin. Habillez-vous en couches ; il fait glacial dans l'air du désert avant l'aube, mais la nacelle devient assez chaude une fois le soleil levé et les brûleurs allumés."
    },
    "es": {
    "title": "Cielo Abierto: Globo Aerostático sobre el Atlas",
    "desc": "Presencia el amanecer sobre las estribaciones de las montañas del Atlas en un inolvidable vuelo en globo desde Marrakech.",
    "fullBody": "Hay un silencio profundo que acompaña el flotar a 3.000 pies sobre la tierra, roto solo por el estallido ocasional del quemador. Mientras te deslizas sobre las montañas Jbilet al norte de Marrakech, el paisaje cambia de desierto rocoso a exuberantes olivares. El contraste de la tierra roja contra las montañas del Atlas cubiertas de nieve en la distancia crea un lienzo soñado para cualquier fotógrafo.\n\nLa experiencia es lujosa de principio a fin. Te recogen en Agadir muy temprano para llegar a Marrakech al amanecer. Al aterrizar, es tradición disfrutar de un 'desayuno bereber' en una carpa real, con msemmen (panqueques), miel local y té a la menta fresco, a menudo organizado por residentes de los pueblos locales que acabas de sobrevolar.\n\nConsejo práctico: Este es un compromiso de día completo desde Agadir debido al tiempo de viaje (3 horas por trayecto hasta el sitio de lanzamiento). La hora de despertarse suele ser alrededor de las 4:00 AM. Vístete por capas; hace mucho frío en el aire del desierto antes del amanecer, pero la cesta del globo se calienta bastante una vez que sale el sol y se encienden los quemadores."
    }
    },
    {
    "slug": "authentic-tagine-cooking-class-agadir",
    "image": "https://images.unsplash.com/photo-1511690656952-34342d2c20f0?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 45,
    "en": {
    "title": "Taste of Morocco: Authentic Tagine Cooking Class",
    "desc": "Learn the secrets of preserved lemons and saffron in a hands-on cooking workshop at a local Berber farm.",
    "fullBody": "Cooking in Morocco is an act of love and patience. In this class, held in a traditional riad or a farm on the outskirts of Agadir, the air is heavy with the aromas of roasting cumin, ginger, and turmeric. You aren't just watching a chef; you are chopping the parsley, arranging the conical display of vegetables, and managing the charcoal fire of the majmar (clay brazier).\n\nThe experience typically begins with a guided trip to the market to select fresh produce. You'll learn how to identify the best zucchini and how to bargain for spices. Back at the kitchen, the highlight is learning to make 'Charmoula', the famous Moroccan marinade, and baking your own Khobz (bread) in a wood-fired oven.\n\nPractical advice: Come hungry, as the meal you cook is your lunch. This is a fantastic activity for vegetarians and vegans, as Vegetable Tagine is a staple dish that requires no modification to be delicious. Classes usually start at 10:00 AM and finish around 2:00 PM after the meal."
    },
    "fr": {
    "title": "Goût du Maroc : Cours de Cuisine Authentique de Tajine",
    "desc": "Apprenez les secrets des citrons confits et du safran lors d'un atelier de cuisine pratique dans une ferme berbère locale.",
    "fullBody": "Cuisiner au Maroc est un acte d'amour et de patience. Dans ce cours, organisé dans un riad traditionnel ou une ferme en périphérie d'Agadir, l'air est chargé des arômes de cumin grillé, de gingembre et de curcuma. Vous ne regardez pas simplement un chef ; vous hachez le persil, arrangez la présentation conique des légumes et gérez le feu de charbon du majmar (brasero en argile).\n\nL'expérience commence généralement par une visite guidée au marché pour sélectionner des produits frais. Vous apprendrez à identifier les meilleures courgettes et à marchander les épices. De retour en cuisine, le moment fort est l'apprentissage de la 'Charmoula', la célèbre marinade marocaine, et la cuisson de votre propre Khobz (pain) dans un four à bois.\n\nConseils pratiques : Venez l'estomac vide, car le repas que vous cuisinez sera votre déjeuner. C'est une activité fantastique pour les végétariens et les végétaliens, car le Tajine de légumes est un plat de base qui ne nécessite aucune modification pour être délicieux. Les cours commencent généralement à 10h00 et se terminent vers 14h00 après le repas."
    },
    "es": {
    "title": "Sabor de Marruecos: Clase Auténtica de Tajine",
    "desc": "Aprende los secretos de los limones en conserva y el azafrán en un taller de cocina práctico en una granja bereber local.",
    "fullBody": "Cocinar en Marruecos es un acto de amor y paciencia. En esta clase, celebrada en un riad tradicional o una granja a las afueras de Agadir, el aire está cargado con los aromas de comino tostado, jengibre y cúrcuma. No solo estás mirando a un chef; estás picando el perejil, organizando la exhibición cónica de verduras y manejando el fuego de carbón del majmar (brasero de arcilla).\n\nLa experiencia generalmente comienza con un viaje guiado al mercado para seleccionar productos frescos. Aprenderás a identificar los mejores calabacines y cómo regatear especias. De vuelta en la cocina, lo más destacado es aprender a hacer 'Charmoula', la famosa marinada marroquí, y hornear tu propio Khobz (pan) en un horno de leña.\n\nConsejo práctico: Ven con hambre, ya que la comida que cocines será tu almuerzo. Esta es una actividad fantástica para vegetarianos y veganos, ya que el Tajine de verduras es un plato básico que no requiere modificaciones para ser delicioso. Las clases suelen comenzar a las 10:00 AM y terminan alrededor de las 14:00 PM después de la comida."
    }
    },
    {
    "slug": "quad-biking-agadir-dunes",
    "image": "https://images.unsplash.com/photo-1543831828-56eb01e4a643?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 40,
    "en": {
    "title": "Adrenaline Rush: Quad Biking the Sand Dunes",
    "desc": "Tear through the pre-Saharan terrain and golden sand dunes on a high-speed quad biking adventure.",
    "fullBody": "Feel the raw power of the engine as you navigate the rugged terrain of the Takkat and Sidi Toual regions. This isn't just driving in circles; it's an exploration of the diverse landscapes surrounding Agadir, shifting from argan tree forests to vertical sand dunes that hug the coastline. The dust kicking up behind you adds to the 'Mad Max' atmosphere of the adventure.\n\nHalfway through the adrenaline-fueled ride, the engines are cut for a peaceful stop at a local Berber house. Here, the dust settles as you enjoy traditional mint tea and homemade bread with Amlou (almond, honey, and argan spread), offering a stark, quiet contrast to the roar of the quads.\n\nPractical advice: You will get dirty. Very dirty. Wear old clothes that you don't mind getting dusty or muddy. The operators provide helmets and goggles, but bringing your own sunglasses is a good idea for eye protection when the goggles fog up. Long pants are mandatory to protect your legs from engine heat."
    },
    "fr": {
    "title": "Poussée d'Adrénaline : Quad dans les Dunes",
    "desc": "Foncez à travers le terrain pré-saharien et les dunes de sable doré lors d'une aventure en quad à grande vitesse.",
    "fullBody": "Sentez la puissance brute du moteur alors que vous naviguez sur le terrain accidenté des régions de Takkat et Sidi Toual. Ce n'est pas juste tourner en rond ; c'est une exploration des paysages diversifiés entourant Agadir, passant des forêts d'arganiers aux dunes de sable verticales qui longent le littoral. La poussière qui se soulève derrière vous ajoute à l'atmosphère 'Mad Max' de l'aventure.\n\nÀ mi-chemin de cette course pleine d'adrénaline, les moteurs sont coupés pour une halte paisible dans une maison berbère locale. Ici, la poussière retombe alors que vous dégustez un thé à la menthe traditionnel et du pain maison avec de l'Amlou (pâte à tartiner aux amandes, miel et argan), offrant un contraste saisissant et calme avec le rugissement des quads.\n\nConseils pratiques : Vous allez vous salir. Vraiment vous salir. Portez de vieux vêtements que vous ne craignez pas de voir couverts de poussière ou de boue. Les opérateurs fournissent des casques et des lunettes, mais apporter vos propres lunettes de soleil est une bonne idée pour protéger vos yeux si les lunettes de protection s'embuent. Les pantalons longs sont obligatoires pour protéger vos jambes de la chaleur du moteur."
    },
    "es": {
    "title": "Subidón de Adrenalina: Quad en las Dunas de Arena",
    "desc": "Atraviesa el terreno presahariano y las dunas de arena dorada en una aventura de quad a alta velocidad.",
    "fullBody": "Siente la potencia bruta del motor mientras navegas por el terreno accidentado de las regiones de Takkat y Sidi Toual. Esto no es solo conducir en círculos; es una exploración de los diversos paisajes que rodean Agadir, cambiando de bosques de árboles de argán a dunas de arena verticales que abrazan la costa. El polvo que se levanta detrás de ti se suma a la atmósfera 'Mad Max' de la aventura.\n\nA mitad del recorrido lleno de adrenalina, los motores se apagan para una parada pacífica en una casa bereber local. Aquí, el polvo se asienta mientras disfrutas del tradicional té a la menta y pan casero con Amlou (crema de almendras, miel y argán), ofreciendo un marcado y tranquilo contraste con el rugido de los quads.\n\nConsejo práctico: Te vas a ensuciar. Mucho. Usa ropa vieja que no te importe que se llene de polvo o barro. Los operadores proporcionan cascos y gafas, pero traer tus propias gafas de sol es una buena idea para proteger los ojos si las gafas protectoras se empañan. Los pantalones largos son obligatorios para proteger tus piernas del calor del motor."
    }
    },
    {
    "slug": "legzira-beach-arches-day-trip",
    "image": "https://images.unsplash.com/photo-1539678050869-96dbdbf43697?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 55,
    "en": {
    "title": "Red Rock Wonder: Day Trip to Legzira Beach",
    "desc": "Walk beneath the colossal red stone arches of Legzira, a geological marvel on the southern Atlantic coast.",
    "fullBody": "Arriving at Legzira feels like stepping onto the surface of Mars, if Mars had an ocean. The massive sedimentary rock arches glow an intense red in the afternoon sun, forged by thousands of years of erosion. It is a raw, windy, and utterly spectacular coastline that attracts geologists and dreamers alike. The scale of the arches makes humans look like ants in comparison.\n\nSituated near the former Spanish enclave of Sidi Ifni, the beach offers more than just rocks. Small, makeshift restaurants built into the cliffside serve incredibly fresh grilled sardines and sea bream, caught just meters away. It is less commercial than Agadir, offering a glimpse into the slower pace of the south.\n\nPractical advice: The drive from Agadir is long (about 3 hours each way), so prepare for a full day out. Crucially, you must check the tide tables before you go. At high tide, the ocean completely cuts off access to the arches, making the walk dangerous or impossible. Aim to arrive at low tide for the full experience."
    },
    "fr": {
    "title": "Merveille de Roche Rouge : Excursion à la Plage de Legzira",
    "desc": "Marchez sous les colossales arches de pierre rouge de Legzira, une merveille géologique sur la côte atlantique sud.",
    "fullBody": "Arriver à Legzira donne l'impression de débarquer sur la surface de Mars, si Mars avait un océan. Les massives arches de roches sédimentaires brillent d'un rouge intense sous le soleil de l'après-midi, forgées par des milliers d'années d'érosion. C'est un littoral brut, venteux et absolument spectaculaire qui attire autant les géologues que les rêveurs. L'échelle des arches fait paraître les humains minuscules en comparaison.\n\nSituée près de l'ancienne enclave espagnole de Sidi Ifni, la plage offre plus que de simples rochers. De petits restaurants de fortune construits à flanc de falaise servent des sardines grillées et des dorades incroyablement fraîches, pêchées à quelques mètres de là. C'est moins commercial qu'Agadir, offrant un aperçu du rythme plus lent du sud.\n\nConseils pratiques : Le trajet depuis Agadir est long (environ 3 heures aller simple), préparez-vous donc à une journée complète. Crucial : vous devez vérifier les horaires des marées avant de partir. À marée haute, l'océan coupe complètement l'accès aux arches, rendant la promenade dangereuse ou impossible. Visez une arrivée à marée basse pour profiter pleinement de l'expérience."
    },
    "es": {
    "title": "Maravilla de Roca Roja: Excursión a la Playa de Legzira",
    "desc": "Camina bajo los colosales arcos de piedra roja de Legzira, una maravilla geológica en la costa atlántica sur.",
    "fullBody": "Llegar a Legzira es como pisar la superficie de Marte, si Marte tuviera un océano. Los enormes arcos de roca sedimentaria brillan con un rojo intenso bajo el sol de la tarde, forjados por miles de años de erosión. Es una costa cruda, ventosa y absolutamente espectacular que atrae tanto a geólogos como a soñadores. La escala de los arcos hace que los humanos parezcan hormigas en comparación.\n\nSituada cerca del antiguo enclave español de Sidi Ifni, la playa ofrece algo más que rocas. Pequeños restaurantes improvisados construidos en la ladera del acantilado sirven sardinas y doradas a la parrilla increíblemente frescas, capturadas a pocos metros de distancia. Es menos comercial que Agadir, ofreciendo un vistazo al ritmo más lento del sur.\n\nConsejo práctico: El viaje desde Agadir es largo (unas 3 horas por trayecto), así que prepárate para un día completo. Fundamental: debes consultar las tablas de mareas antes de ir. Con la marea alta, el océano corta completamente el acceso a los arcos, haciendo que el paseo sea peligroso o imposible. Intenta llegar con la marea baja para disfrutar de la experiencia completa."
    }
    },
    {
    "slug": "ouzoud-waterfalls-hike-atlas",
    "image": "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 60,
    "en": {
    "title": "Nature's Power: Hiking the Ouzoud Waterfalls",
    "desc": "Trek to the base of North Africa's highest waterfalls and meet the resident Barbary macaque monkeys.",
    "fullBody": "The Ouzoud Waterfalls are a thundering display of nature's power, cascading 110 meters down into the canyon below. The mist rising from the impact creates almost permanent rainbows, adding a mystical touch to the verdant, moss-covered surroundings. Unlike the arid regions of Morocco, this area is lush with olive trees and carob, providing a cool, shaded environment perfect for hiking.\n\nA guided hike takes you from the top of the falls down a winding path to the bottom pools. Here, you can board small, gaudily decorated rafts that row you dangerously close to the spray for a refreshing shower. Keep your snacks hidden—wild Barbary macaque monkeys roam the paths and are notoriously cheeky thieves, though they pose great photo opportunities.\n\nPractical advice: It is a very long day trip (early departure is essential), but worth the miles. Wear hiking boots or trainers with good grip; the clay paths get slippery near the spray. Avoid visiting on weekends in July and August, as it becomes a popular swimming spot for locals and can get very crowded."
    },
    "fr": {
    "title": "Puissance de la Nature : Randonnée aux Cascades d'Ouzoud",
    "desc": "Randonnez jusqu'au pied des plus hautes cascades d'Afrique du Nord et rencontrez les singes macaques de Barbarie.",
    "fullBody": "Les cascades d'Ouzoud sont une démonstration tonitruante de la puissance de la nature, tombant de 110 mètres dans le canyon en contrebas. La brume s'élevant de l'impact crée des arcs-en-ciel quasi permanents, ajoutant une touche mystique à l'environnement verdoyant et moussu. Contrairement aux régions arides du Maroc, cette zone est riche en oliviers et caroubiers, offrant un environnement frais et ombragé parfait pour la randonnée.\n\nUne randonnée guidée vous emmène du haut des chutes jusqu'aux bassins inférieurs par un sentier sinueux. Là, vous pouvez embarquer sur de petits radeaux décorés de façon kitch qui vous rament dangereusement près des embruns pour une douche rafraîchissante. Cachez vos collations — les macaques de Barbarie sauvages parcourent les sentiers et sont des voleurs notoirement effrontés, bien qu'ils offrent de superbes opportunités photo.\n\nConseils pratiques : C'est une très longue excursion d'une journée (départ tôt essentiel), mais qui vaut les kilomètres. Portez des chaussures de randonnée ou des baskets avec une bonne adhérence ; les sentiers argileux deviennent glissants près des embruns. Évitez de visiter le week-end en juillet et août, car cela devient un lieu de baignade populaire pour les habitants et peut être très bondé."
    },
    "es": {
    "title": "Poder de la Naturaleza: Senderismo en las Cascadas de Ouzoud",
    "desc": "Camina hasta la base de las cascadas más altas del norte de África y conoce a los monos macacos de Berbería residentes.",
    "fullBody": "Las cascadas de Ouzoud son una exhibición atronadora del poder de la naturaleza, cayendo 110 metros hacia el cañón de abajo. La niebla que se levanta del impacto crea arcoíris casi permanentes, añadiendo un toque místico al entorno verde y cubierto de musgo. A diferencia de las regiones áridas de Marruecos, esta zona es exuberante con olivos y algarrobos, proporcionando un ambiente fresco y sombreado perfecto para el senderismo.\n\nUna caminata guiada te lleva desde la cima de las cataratas por un sendero sinuoso hasta las piscinas inferiores. Allí, puedes subirte a pequeñas balsas decoradas llamativamente que te llevan peligrosamente cerca del rocío para una ducha refrescante. Esconde tus bocadillos: los monos macacos de Berbería salvajes recorren los caminos y son ladrones notoriamente descarados, aunque ofrecen excelentes oportunidades para fotos.\n\nConsejo práctico: Es una excursión de un día muy largo (es esencial salir temprano), pero vale la pena el viaje. Usa botas de montaña o zapatillas con buen agarre; los caminos de arcilla se vuelven resbaladizos cerca del rocío. Evita visitar los fines de semana en julio y agosto, ya que se convierte en un lugar de baño popular para los lugareños y puede estar muy concurrido."
    }
    },
    {
    "slug": "star-gazing-agafay-desert",
    "image": "https://images.unsplash.com/photo-1542614948-692795a973a2?auto=format&fit=crop&w=1200&q=80",
    "cardPrice": 90,
    "en": {
    "title": "Celestial Nights: Star Gazing in Agafay Desert",
    "desc": "Enjoy a candlelit dinner and an astronomy lesson under the infinite stars of the Agafay stone desert.",
    "fullBody": "The Agafay Desert is not a sea of sand, but a vast, dramatic expanse of stone dunes that look like the surface of the moon. At night, devoid of the light pollution from the cities, the sky opens up into a 360-degree dome of stars. It is an atmosphere of absolute silence and romance, often illuminated only by lanterns and the Milky Way.\n\nThe evening typically involves a transfer to a luxury desert camp. You are welcomed with dates and milk before sitting down to a traditional Moroccan feast in a Berber tent or under the open sky. After dinner, an astronomer guides you through the constellations using a high-powered telescope, explaining how ancient caravans used the stars for navigation.\n\nPractical advice: Located about 45 minutes from Marrakech (and accessible from Agadir as a long day/overnight trip), Agafay gets surprisingly cold at night, even after hot days. Bring a warm jacket and a scarf. While the ground is stony, the camps are very comfortable, but sensible closed-toe shoes are recommended for walking around the camp perimeter."
    },
    "fr": {
    "title": "Nuits Célestes : Observation des Étoiles dans le Désert d'Agafay",
    "desc": "Profitez d'un dîner aux chandelles et d'une leçon d'astronomie sous les étoiles infinies du désert de pierre d'Agafay.",
    "fullBody": "Le désert d'Agafay n'est pas une mer de sable, mais une vaste étendue spectaculaire de dunes de pierre qui ressemblent à la surface de la lune. La nuit, dépourvu de la pollution lumineuse des villes, le ciel s'ouvre en un dôme d'étoiles à 360 degrés. C'est une atmosphère de silence absolu et de romantisme, souvent éclairée uniquement par des lanternes et la Voie Lactée.\n\nLa soirée implique généralement un transfert vers un camp de luxe dans le désert. Vous êtes accueilli avec des dattes et du lait avant de vous asseoir pour un festin marocain traditionnel sous une tente berbère ou à ciel ouvert. Après le dîner, un astronome vous guide à travers les constellations à l'aide d'un télescope puissant, expliquant comment les anciennes caravanes utilisaient les étoiles pour la navigation.\n\nConseils pratiques : Situé à environ 45 minutes de Marrakech (et accessible depuis Agadir en longue excursion d'une journée ou avec nuitée), Agafay devient étonnamment froid la nuit, même après des journées chaudes. Apportez une veste chaude et une écharpe. Bien que le sol soit pierreux, les camps sont très confortables, mais des chaussures fermées sont recommandées pour marcher autour du périmètre du camp."
    },
    "es": {
    "title": "Noches Celestiales: Observación de Estrellas en el Desierto de Agafay",
    "desc": "Disfruta de una cena a la luz de las velas y una lección de astronomía bajo las infinitas estrellas del desierto de piedra de Agafay.",
    "fullBody": "El desierto de Agafay no es un mar de arena, sino una vasta y espectacular extensión de dunas de piedra que parecen la superficie de la luna. Por la noche, libre de la contaminación lumínica de las ciudades, el cielo se abre en una cúpula de estrellas de 360 grados. Es una atmósfera de silencio absoluto y romance, a menudo iluminada solo por linternas y la Vía Láctea.\n\nLa velada suele implicar un traslado a un campamento de lujo en el desierto. Te reciben con dátiles y leche antes de sentarte a disfrutar de un festín tradicional marroquí en una tienda bereber o bajo el cielo abierto. Después de la cena, un astrónomo te guía a través de las constelaciones utilizando un telescopio de alta potencia, explicando cómo las antiguas caravanas usaban las estrellas para navegar.\n\nConsejo práctico: Situado a unos 45 minutos de Marrakech (y accesible desde Agadir como una excursión larga de un día o con pernoctación), Agafay se vuelve sorprendentemente frío por la noche, incluso después de días calurosos. Lleva una chaqueta abrigada y una bufanda. Aunque el suelo es pedregoso, los campamentos son muy cómodos, pero se recomienda calzado cerrado y sensato para caminar por el perímetro del campamento."
    }
    }
    ]